name: Publish vue3-map-chart

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # docs https://pnpm.io/continuous-integration#github-actions
        with:
            version: 8  # Optional: specify a pnpm version

      # 2. Set up Node.js and configure the registry to GitHub Packages
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com/"

      # 3. Install dependencies from the monorepo root
      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies in vue3-map-chart package
        working-directory: packages/vue3-map-chart
        run: pnpm install

      # 4. Build the vue3-map-chart package
      - name: Build vue3-map-chart
        working-directory: packages/vue3-map-chart
        run: pnpm build

      # 5. Publish the package to GitHub Packages
      - name: Publish vue3-map-chart
        working-directory: packages/vue3-map-chart
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
